# Generated by Django 5.2.7 on 2025-11-20 22:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s-]*$', 'Seules les lettres, espaces et tirets sont autorisés.')], verbose_name='Nom')),
                ('food_type', models.CharField(choices=[('PROT', 'Protein'), ('CARB', 'Carbohydrate'), ('VEG', 'Vegetable'), ('FRUIT', 'Fruit'), ('HFAT', 'Healthy Fat'), ('OTHER', 'Other')], max_length=5, verbose_name="Type d'aliment")),
                ('diet_type', models.CharField(choices=[('OMNI', 'Omnivore'), ('VEG', 'Vegetarian'), ('VEGAN', 'Vegan')], max_length=5, verbose_name='Type de régime')),
                ('default_unit', models.CharField(choices=[('G', 'Gram'), ('P', 'Piece')], max_length=2, verbose_name='Unité par défaut')),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Protéines pour 100g')),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Glucides pour 100g')),
                ('fats_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Lipides pour 100g')),
                ('average_piece_weight', models.IntegerField(default=0, verbose_name='Poids moyen par pièce (g)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'ordering': ['name'],
                'unique_together': {('name', 'food_type')},
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Plat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlateIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient', verbose_name='Ingrédient')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='nutrition.plate', verbose_name='Plat')),
            ],
            options={
                'verbose_name': 'Ingrédient du plat',
                'verbose_name_plural': 'Ingrédients du plat',
                'unique_together': {('plate', 'ingredient')},
            },
        ),
    ]
